name:                semana2
version:             0.1.0.0
github:              "githubuser/semana2"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/semana2#readme>

dependencies:
- base >= 4.7 && < 5
- tasty
- tasty-hunit
- tasty-quickcheck
- HUnit
- QuickCheck

library:
  source-dirs: src

executables:
  semana2-exe:
    main:                Semana2.lhs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - semana2

tests:
  semana2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - semana2
